gcp_project_id: cloud-computing-project-418718
gcp_bucket: project_bucket_52dfc7cd
region: europe-west3
repository: docker-img
dataset_id: common_ds
main_table_name: main_table
stg_table_name: stg_table