gcp_project_id: cloud-computing-project-418718
gcp_bucket: project_bucket_52dfc7cd
region: europe-west3
repository: docker-img
dataset_id: common_ds
main_table_name: main_table
stg_table_name: stg_table
gcp_serving_bucket: serve_cf_bucket_35ar32da
serve_cf_name: serve-cf
max_serve_cf_instances: 1
serve_cv_available_memory: 256M